language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.5
  - 2.3.1
env:
  global:
    - TESLA_EMAIL=elon.musk@teslamotors.com
    - TESLA_PASS=oilLOL
    - TESLA_CLIENT_ID=1
    - TESLA_CLIENT_SECRET=2
    - TESLA_API_TOKEN=3
notifications:
  email: false
